import { TradeEntry, BehavioralWarning, JournalReport } from './types/journal.types';
export class JournalIntelligence {
  private trades: TradeEntry[] = [];
  addTrade(trade: TradeEntry): void { this.trades.push(trade); }
  detectBehavioralIssues(): BehavioralWarning[] { const warnings: BehavioralWarning[] = []; const now = Date.now(); const oneHourAgo = now - 3600000; const recentTrades = this.trades.filter(t => t.timestamp > oneHourAgo); if (recentTrades.length > 5) warnings.push({ type: 'OVERTRADING', severity: 'HIGH', message: `${recentTrades.length} trades na última hora.`, timestamp: now }); const sorted = [...this.trades].sort((a, b) => b.timestamp - a.timestamp); let consecutiveLosses = 0; for (const t of sorted) { if (t.pnl !== undefined && t.pnl < 0) consecutiveLosses++; else break; } if (consecutiveLosses >= 3) warnings.push({ type: 'REVENGE_TRADING', severity: 'HIGH', message: `${consecutiveLosses} perdas consecutivas.`, timestamp: now }); const lowQuality = this.trades.filter(t => t.confidence < 40); if (lowQuality.length > this.trades.length * 0.3 && this.trades.length > 5) warnings.push({ type: 'LOW_QUALITY_SETUP', severity: 'MEDIUM', message: `${lowQuality.length} trades com confiança baixa.`, timestamp: now }); return warnings; }
  generateWeeklyReport(): JournalReport { return this.generateReport('WEEKLY'); }
  generateMonthlyReport(): JournalReport { return this.generateReport('MONTHLY'); }
  private generateReport(period: 'WEEKLY' | 'MONTHLY'): JournalReport { const completed = this.trades.filter(t => t.exitPrice !== undefined); const wins = completed.filter(t => (t.pnl ?? 0) > 0).length; const totalPnl = completed.reduce((s, t) => s + (t.pnl ?? 0), 0); const avgReturn = completed.length > 0 ? completed.reduce((s, t) => s + (t.pnl ?? 0), 0) / completed.length : 0; const warnings = this.detectBehavioralIssues(); const suggestions: string[] = []; if (warnings.some(w => w.type === 'OVERTRADING')) suggestions.push('Reduzir frequência de trades.'); if (warnings.some(w => w.type === 'REVENGE_TRADING')) suggestions.push('Implementar pausa obrigatória após perdas consecutivas.'); return { period, totalTrades: this.trades.length, winRate: completed.length > 0 ? wins / completed.length : 0, avgReturn, pnl: totalPnl, behavioralWarnings: warnings, improvementSuggestions: suggestions }; }
}
