import { GammaExposure, DeltaExposure, PutCallRatio, DealerPositioning, MaxPain, ExpectedMove, VolatilityRegimeDeriv } from '../types/derivatives.types';
export class MockDerivativesAdapter {
  async fetchGammaExposure(xauPrice: number): Promise<GammaExposure> { const strikes = [xauPrice - 50, xauPrice - 20, xauPrice, xauPrice + 20, xauPrice + 50]; const gammaPerStrike: Record<number, number> = {}; for (const k of strikes) { gammaPerStrike[k] = Math.random() * 100 - 50; } const totalGamma = Object.values(gammaPerStrike).reduce((a, b) => a + b, 0); return { totalGamma, gammaPerStrike, flipPoint: xauPrice + totalGamma * 0.1, regime: totalGamma > 0 ? 'POSITIVE_GAMMA' : 'NEGATIVE_GAMMA' }; }
  async fetchDeltaExposure(): Promise<DeltaExposure> { return { totalDelta: Math.random() * 200 - 100, deltaByExpiry: { '1W': Math.random() * 50 - 25, '1M': Math.random() * 80 - 40 }, netDirection: Math.random() > 0.5 ? 'LONG' : 'SHORT' }; }
  async fetchPutCallRatio(): Promise<PutCallRatio> { const ratio = 0.5 + Math.random() * 1.5; return { ratio, signal: ratio > 1 ? 'BEARISH' : ratio < 0.7 ? 'BULLISH' : 'NEUTRAL', volumePut: Math.floor(Math.random() * 5000), volumeCall: Math.floor(Math.random() * 5000) }; }
  async fetchDealerPositioning(): Promise<DealerPositioning> { return { netPosition: Math.random() * 200 - 100, gammaProfile: Math.random() > 0.5 ? 'LONG_GAMMA' : 'SHORT_GAMMA', keyLevels: { support: 4100 + Math.random() * 100, resistance: 4200 + Math.random() * 100 } }; }
  async fetchMaxPain(currentPrice: number): Promise<MaxPain> { const maxPainStrike = currentPrice + (Math.random() - 0.5) * 80; const distancePct = ((maxPainStrike - currentPrice) / currentPrice) * 100; return { maxPainStrike, currentPrice, distancePct, magnet: Math.abs(distancePct) < 1.5 }; }
  async fetchExpectedMove(currentPrice: number): Promise<ExpectedMove> { const move = currentPrice * 0.015; return { expectedMoveUp: currentPrice + move, expectedMoveDown: currentPrice - move, impliedRange: [currentPrice - move, currentPrice + move] }; }
  async fetchVolatilityRegime(): Promise<VolatilityRegimeDeriv> { const roll = Math.random(); return { current: roll > 0.8 ? 'HIGH_VOL' : roll > 0.4 ? 'NORMAL_VOL' : 'LOW_VOL', percentile: Math.floor(Math.random() * 100), termStructure: Math.random() > 0.5 ? 'CONTANGO' : 'BACKWARDATION' }; }
}
